server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgressql://localhost:5432/postgres
    username: postgres
    password: 123456
  jpa:
    show-sql: true
    database-plataform: org.hibernate.dialect.PostgresSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
